name: canakit piz2w
baseUrl: https://www.canakit.com/raspberry-pi-zero-2-w.html?cid=usd&src=raspberrypi
outOfStockIndicator:
    styleAttributeName: "#ProductAddToCartDiv > a > span"
    indicator: Pre-Orders Sold Out
