name: canakit rpi4 4gb
baseUrl: https://www.canakit.com/raspberry-pi-4-4gb.html?cid=usd&src=raspberrypi
outOfStockIndicator:
  styleAttributeName: "#ProductAddToCartDiv > a > span"
  indicator: Pre-Orders Sold Out
