name: chicagodist rpi4 8gb
baseUrl: https://chicagodist.com/products/raspberry-pi-4-model-b-8gb?src=raspberrypi
outOfStockIndicator:
  styleAttributeName: "#shopify-section-product-template > div > div > div > div.product__description.seven.columns.omega.product__description--right > p.modal_price > span"
  indicator: Sold Out
