# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v -o pi-stock-checker main.go

      - name: Test
        run: go test -v ./...

      - name: Archive production build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            pi-stock-checker
            config

      - name: Download results and run
        uses: actions/download-artifact@v3
        with:
          name: build
      - shell: bash
        run: ./pi-stock-checker -cd config
